### ISSUE TITLE
How to install this tool without cargo and snap

### ISSUE THREAD

**Issue by sanyalab** [amaurypm/pseqsid#1]
Hello,

I am not very familiar cargo and snap. How do I install this tool using python commands? I have downloaded and unpacked the zip file. Can you please guide me step by step what to do next? I am on Ubuntu machine.

Thanks
Abhijit

**Comment by amaurypm** [comment]
Hello @sanyalab ,

If you are on Ubuntu you just have to do:

```
sudo snap install pseqsid
```

This is not a python script, so you do not install it with python commands.

Best regards,
Amaury

**Comment by amaurypm** [comment]
Closed.

**Comment by sanyalab** [comment]
Can I do this via conda? I do not have sudo rights.
![image](https://github.com/user-attachments/assets/e079866c-290f-4575-aa13-4ac0b1e5b629)
I see the above when I search anaconda for snap. Do I install the second from top? and then do `snap install pseqsid`
